// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Type specifies all possible transaction types
type Transaction_Type int32

const (
	Transaction_GENESIS            Transaction_Type = 0
	Transaction_CREATE_ACCOUNT     Transaction_Type = 1
	Transaction_MERGE_ACCOUNT      Transaction_Type = 2
	Transaction_SEND               Transaction_Type = 3
	Transaction_SET_VALIDATOR_FLAG Transaction_Type = 4
	Transaction_VOTE_VALIDATOR     Transaction_Type = 5
	Transaction_ADD_SIGNER         Transaction_Type = 6
	Transaction_REMOVE_SIGNER      Transaction_Type = 7
	Transaction_SET_THRESHOLD      Transaction_Type = 8
	Transaction_SET_DATA           Transaction_Type = 9
	Transaction_EXECUTE            Transaction_Type = 10
)

var Transaction_Type_name = map[int32]string{
	0:  "GENESIS",
	1:  "CREATE_ACCOUNT",
	2:  "MERGE_ACCOUNT",
	3:  "SEND",
	4:  "SET_VALIDATOR_FLAG",
	5:  "VOTE_VALIDATOR",
	6:  "ADD_SIGNER",
	7:  "REMOVE_SIGNER",
	8:  "SET_THRESHOLD",
	9:  "SET_DATA",
	10: "EXECUTE",
}

var Transaction_Type_value = map[string]int32{
	"GENESIS":            0,
	"CREATE_ACCOUNT":     1,
	"MERGE_ACCOUNT":      2,
	"SEND":               3,
	"SET_VALIDATOR_FLAG": 4,
	"VOTE_VALIDATOR":     5,
	"ADD_SIGNER":         6,
	"REMOVE_SIGNER":      7,
	"SET_THRESHOLD":      8,
	"SET_DATA":           9,
	"EXECUTE":            10,
}

func (x Transaction_Type) String() string {
	return proto.EnumName(Transaction_Type_name, int32(x))
}

func (Transaction_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 0}
}

// Type is a enum of all valid smart contract runtimes
type Transaction_ExecuteContent_Type int32

const (
	Transaction_ExecuteContent_JS   Transaction_ExecuteContent_Type = 0
	Transaction_ExecuteContent_WASM Transaction_ExecuteContent_Type = 1
)

var Transaction_ExecuteContent_Type_name = map[int32]string{
	0: "JS",
	1: "WASM",
}

var Transaction_ExecuteContent_Type_value = map[string]int32{
	"JS":   0,
	"WASM": 1,
}

func (x Transaction_ExecuteContent_Type) String() string {
	return proto.EnumName(Transaction_ExecuteContent_Type_name, int32(x))
}

func (Transaction_ExecuteContent_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 10, 0}
}

type Signer struct {
	// name of the signer, only used to identify signers in the context of the containing account
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// signature_algorithm of the signer, e.g. 'ed25519', 'ecdsa', 'sphinx'... Lookup liboqs for more types!
	SignatureAlgorithm string `protobuf:"bytes,2,opt,name=signature_algorithm,json=signatureAlgorithm,proto3" json:"signature_algorithm,omitempty"`
	// hash_algorithm specifies the hash algorithm for this signer
	HashAlgorithm string `protobuf:"bytes,3,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"`
	// pubkey is the public key of the signer
	Pubkey []byte `protobuf:"bytes,4,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// weight is the weight of a signature of this signer
	Weight               uint64   `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signer) Reset()         { *m = Signer{} }
func (m *Signer) String() string { return proto.CompactTextString(m) }
func (*Signer) ProtoMessage()    {}
func (*Signer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *Signer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signer.Unmarshal(m, b)
}
func (m *Signer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signer.Marshal(b, m, deterministic)
}
func (m *Signer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signer.Merge(m, src)
}
func (m *Signer) XXX_Size() int {
	return xxx_messageInfo_Signer.Size(m)
}
func (m *Signer) XXX_DiscardUnknown() {
	xxx_messageInfo_Signer.DiscardUnknown(m)
}

var xxx_messageInfo_Signer proto.InternalMessageInfo

func (m *Signer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Signer) GetSignatureAlgorithm() string {
	if m != nil {
		return m.SignatureAlgorithm
	}
	return ""
}

func (m *Signer) GetHashAlgorithm() string {
	if m != nil {
		return m.HashAlgorithm
	}
	return ""
}

func (m *Signer) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *Signer) GetWeight() uint64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Account struct {
	// id of the account
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// description contains a short description of this account
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// set of signers for this account, indexed by name
	Signers map[string]*Signer `protobuf:"bytes,3,rep,name=signers,proto3" json:"signers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// threshold specifies how many signatures are required to successfully transmit a transaction
	// if the sum of the weights of valid signatures is greater or equal than this, the TX will succeed
	Threshold uint64 `protobuf:"varint,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// balance contains the amount of native tokens assigned to this account
	Balance uint64 `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	// is_validator indicates if the account is working as a validator for the network
	IsValidator bool `protobuf:"varint,6,opt,name=is_validator,json=isValidator,proto3" json:"is_validator,omitempty"`
	// vote contains the id of the account for which this account is voting
	Vote string `protobuf:"bytes,7,opt,name=vote,proto3" json:"vote,omitempty"`
	// created_at tells you when this account has been created
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Account) GetSigners() map[string]*Signer {
	if m != nil {
		return m.Signers
	}
	return nil
}

func (m *Account) GetThreshold() uint64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *Account) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetIsValidator() bool {
	if m != nil {
		return m.IsValidator
	}
	return false
}

func (m *Account) GetVote() string {
	if m != nil {
		return m.Vote
	}
	return ""
}

func (m *Account) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

// Transaction is used to update the distributed ledger state
type Transaction struct {
	// These are the actual fields of a transaction
	// id is a unique identifier for the transaction
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type specifies what kind of transaction this is
	Type Transaction_Type `protobuf:"varint,2,opt,name=type,proto3,enum=Transaction_Type" json:"type,omitempty"`
	// source_account is the address of the source account of this transaction
	SourceAccount string `protobuf:"bytes,3,opt,name=source_account,json=sourceAccount,proto3" json:"source_account,omitempty"`
	// created_at tells you, you already guess it, when this tx has been created
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// signatures contains the signatures for this transaction indexed by name of the signer
	Signatures map[string][]byte `protobuf:"bytes,5,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// fees contains the amount of native tokens used to pay for this transaction
	Fees uint64 `protobuf:"varint,6,opt,name=fees,proto3" json:"fees,omitempty"`
	// content contains the type specific payload for the transaction
	//
	// Types that are valid to be assigned to Content:
	//	*Transaction_CreateAccountContent_
	//	*Transaction_MergeAccountContent_
	//	*Transaction_SendContent
	//	*Transaction_SetValidatorFlagContent_
	//	*Transaction_VoteValidatorContent_
	//	*Transaction_AddSignerContent_
	//	*Transaction_RemoveSignerContent_
	//	*Transaction_SetThresholdContent_
	//	*Transaction_SetDataContent_
	//	*Transaction_ExecuteContent_
	//	*Transaction_GenesisContent_
	Content              isTransaction_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetType() Transaction_Type {
	if m != nil {
		return m.Type
	}
	return Transaction_GENESIS
}

func (m *Transaction) GetSourceAccount() string {
	if m != nil {
		return m.SourceAccount
	}
	return ""
}

func (m *Transaction) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Transaction) GetSignatures() map[string][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *Transaction) GetFees() uint64 {
	if m != nil {
		return m.Fees
	}
	return 0
}

type isTransaction_Content interface {
	isTransaction_Content()
}

type Transaction_CreateAccountContent_ struct {
	CreateAccountContent *Transaction_CreateAccountContent `protobuf:"bytes,7,opt,name=create_account_content,json=createAccountContent,proto3,oneof"`
}

type Transaction_MergeAccountContent_ struct {
	MergeAccountContent *Transaction_MergeAccountContent `protobuf:"bytes,8,opt,name=merge_account_content,json=mergeAccountContent,proto3,oneof"`
}

type Transaction_SendContent struct {
	SendContent *Transaction_SendData `protobuf:"bytes,9,opt,name=send_content,json=sendContent,proto3,oneof"`
}

type Transaction_SetValidatorFlagContent_ struct {
	SetValidatorFlagContent *Transaction_SetValidatorFlagContent `protobuf:"bytes,10,opt,name=set_validator_flag_content,json=setValidatorFlagContent,proto3,oneof"`
}

type Transaction_VoteValidatorContent_ struct {
	VoteValidatorContent *Transaction_VoteValidatorContent `protobuf:"bytes,11,opt,name=vote_validator_content,json=voteValidatorContent,proto3,oneof"`
}

type Transaction_AddSignerContent_ struct {
	AddSignerContent *Transaction_AddSignerContent `protobuf:"bytes,12,opt,name=add_signer_content,json=addSignerContent,proto3,oneof"`
}

type Transaction_RemoveSignerContent_ struct {
	RemoveSignerContent *Transaction_RemoveSignerContent `protobuf:"bytes,13,opt,name=remove_signer_content,json=removeSignerContent,proto3,oneof"`
}

type Transaction_SetThresholdContent_ struct {
	SetThresholdContent *Transaction_SetThresholdContent `protobuf:"bytes,14,opt,name=set_threshold_content,json=setThresholdContent,proto3,oneof"`
}

type Transaction_SetDataContent_ struct {
	SetDataContent *Transaction_SetDataContent `protobuf:"bytes,15,opt,name=set_data_content,json=setDataContent,proto3,oneof"`
}

type Transaction_ExecuteContent_ struct {
	ExecuteContent *Transaction_ExecuteContent `protobuf:"bytes,16,opt,name=execute_content,json=executeContent,proto3,oneof"`
}

type Transaction_GenesisContent_ struct {
	GenesisContent *Transaction_GenesisContent `protobuf:"bytes,17,opt,name=genesis_content,json=genesisContent,proto3,oneof"`
}

func (*Transaction_CreateAccountContent_) isTransaction_Content() {}

func (*Transaction_MergeAccountContent_) isTransaction_Content() {}

func (*Transaction_SendContent) isTransaction_Content() {}

func (*Transaction_SetValidatorFlagContent_) isTransaction_Content() {}

func (*Transaction_VoteValidatorContent_) isTransaction_Content() {}

func (*Transaction_AddSignerContent_) isTransaction_Content() {}

func (*Transaction_RemoveSignerContent_) isTransaction_Content() {}

func (*Transaction_SetThresholdContent_) isTransaction_Content() {}

func (*Transaction_SetDataContent_) isTransaction_Content() {}

func (*Transaction_ExecuteContent_) isTransaction_Content() {}

func (*Transaction_GenesisContent_) isTransaction_Content() {}

func (m *Transaction) GetContent() isTransaction_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Transaction) GetCreateAccountContent() *Transaction_CreateAccountContent {
	if x, ok := m.GetContent().(*Transaction_CreateAccountContent_); ok {
		return x.CreateAccountContent
	}
	return nil
}

func (m *Transaction) GetMergeAccountContent() *Transaction_MergeAccountContent {
	if x, ok := m.GetContent().(*Transaction_MergeAccountContent_); ok {
		return x.MergeAccountContent
	}
	return nil
}

func (m *Transaction) GetSendContent() *Transaction_SendData {
	if x, ok := m.GetContent().(*Transaction_SendContent); ok {
		return x.SendContent
	}
	return nil
}

func (m *Transaction) GetSetValidatorFlagContent() *Transaction_SetValidatorFlagContent {
	if x, ok := m.GetContent().(*Transaction_SetValidatorFlagContent_); ok {
		return x.SetValidatorFlagContent
	}
	return nil
}

func (m *Transaction) GetVoteValidatorContent() *Transaction_VoteValidatorContent {
	if x, ok := m.GetContent().(*Transaction_VoteValidatorContent_); ok {
		return x.VoteValidatorContent
	}
	return nil
}

func (m *Transaction) GetAddSignerContent() *Transaction_AddSignerContent {
	if x, ok := m.GetContent().(*Transaction_AddSignerContent_); ok {
		return x.AddSignerContent
	}
	return nil
}

func (m *Transaction) GetRemoveSignerContent() *Transaction_RemoveSignerContent {
	if x, ok := m.GetContent().(*Transaction_RemoveSignerContent_); ok {
		return x.RemoveSignerContent
	}
	return nil
}

func (m *Transaction) GetSetThresholdContent() *Transaction_SetThresholdContent {
	if x, ok := m.GetContent().(*Transaction_SetThresholdContent_); ok {
		return x.SetThresholdContent
	}
	return nil
}

func (m *Transaction) GetSetDataContent() *Transaction_SetDataContent {
	if x, ok := m.GetContent().(*Transaction_SetDataContent_); ok {
		return x.SetDataContent
	}
	return nil
}

func (m *Transaction) GetExecuteContent() *Transaction_ExecuteContent {
	if x, ok := m.GetContent().(*Transaction_ExecuteContent_); ok {
		return x.ExecuteContent
	}
	return nil
}

func (m *Transaction) GetGenesisContent() *Transaction_GenesisContent {
	if x, ok := m.GetContent().(*Transaction_GenesisContent_); ok {
		return x.GenesisContent
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Transaction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Transaction_CreateAccountContent_)(nil),
		(*Transaction_MergeAccountContent_)(nil),
		(*Transaction_SendContent)(nil),
		(*Transaction_SetValidatorFlagContent_)(nil),
		(*Transaction_VoteValidatorContent_)(nil),
		(*Transaction_AddSignerContent_)(nil),
		(*Transaction_RemoveSignerContent_)(nil),
		(*Transaction_SetThresholdContent_)(nil),
		(*Transaction_SetDataContent_)(nil),
		(*Transaction_ExecuteContent_)(nil),
		(*Transaction_GenesisContent_)(nil),
	}
}

// GenesisContent contains the initial state of the chain
type Transaction_GenesisContent struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Transaction_GenesisContent) Reset()         { *m = Transaction_GenesisContent{} }
func (m *Transaction_GenesisContent) String() string { return proto.CompactTextString(m) }
func (*Transaction_GenesisContent) ProtoMessage()    {}
func (*Transaction_GenesisContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 0}
}

func (m *Transaction_GenesisContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_GenesisContent.Unmarshal(m, b)
}
func (m *Transaction_GenesisContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_GenesisContent.Marshal(b, m, deterministic)
}
func (m *Transaction_GenesisContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_GenesisContent.Merge(m, src)
}
func (m *Transaction_GenesisContent) XXX_Size() int {
	return xxx_messageInfo_Transaction_GenesisContent.Size(m)
}
func (m *Transaction_GenesisContent) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_GenesisContent.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_GenesisContent proto.InternalMessageInfo

func (m *Transaction_GenesisContent) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// CreateAccountContent contains the info that is needed to create a new account
type Transaction_CreateAccountContent struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_CreateAccountContent) Reset()         { *m = Transaction_CreateAccountContent{} }
func (m *Transaction_CreateAccountContent) String() string { return proto.CompactTextString(m) }
func (*Transaction_CreateAccountContent) ProtoMessage()    {}
func (*Transaction_CreateAccountContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 1}
}

func (m *Transaction_CreateAccountContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_CreateAccountContent.Unmarshal(m, b)
}
func (m *Transaction_CreateAccountContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_CreateAccountContent.Marshal(b, m, deterministic)
}
func (m *Transaction_CreateAccountContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_CreateAccountContent.Merge(m, src)
}
func (m *Transaction_CreateAccountContent) XXX_Size() int {
	return xxx_messageInfo_Transaction_CreateAccountContent.Size(m)
}
func (m *Transaction_CreateAccountContent) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_CreateAccountContent.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_CreateAccountContent proto.InternalMessageInfo

func (m *Transaction_CreateAccountContent) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// MergeAccountContent contains the id of the target account
type Transaction_MergeAccountContent struct {
	TargetAccount        string   `protobuf:"bytes,1,opt,name=target_account,json=targetAccount,proto3" json:"target_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_MergeAccountContent) Reset()         { *m = Transaction_MergeAccountContent{} }
func (m *Transaction_MergeAccountContent) String() string { return proto.CompactTextString(m) }
func (*Transaction_MergeAccountContent) ProtoMessage()    {}
func (*Transaction_MergeAccountContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 2}
}

func (m *Transaction_MergeAccountContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_MergeAccountContent.Unmarshal(m, b)
}
func (m *Transaction_MergeAccountContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_MergeAccountContent.Marshal(b, m, deterministic)
}
func (m *Transaction_MergeAccountContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_MergeAccountContent.Merge(m, src)
}
func (m *Transaction_MergeAccountContent) XXX_Size() int {
	return xxx_messageInfo_Transaction_MergeAccountContent.Size(m)
}
func (m *Transaction_MergeAccountContent) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_MergeAccountContent.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_MergeAccountContent proto.InternalMessageInfo

func (m *Transaction_MergeAccountContent) GetTargetAccount() string {
	if m != nil {
		return m.TargetAccount
	}
	return ""
}

// SendData contains the info needed to transfer tokens from one account to another
type Transaction_SendData struct {
	TargetAccount        string   `protobuf:"bytes,1,opt,name=target_account,json=targetAccount,proto3" json:"target_account,omitempty"`
	SendAmount           uint64   `protobuf:"varint,2,opt,name=send_amount,json=sendAmount,proto3" json:"send_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_SendData) Reset()         { *m = Transaction_SendData{} }
func (m *Transaction_SendData) String() string { return proto.CompactTextString(m) }
func (*Transaction_SendData) ProtoMessage()    {}
func (*Transaction_SendData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 3}
}

func (m *Transaction_SendData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_SendData.Unmarshal(m, b)
}
func (m *Transaction_SendData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_SendData.Marshal(b, m, deterministic)
}
func (m *Transaction_SendData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_SendData.Merge(m, src)
}
func (m *Transaction_SendData) XXX_Size() int {
	return xxx_messageInfo_Transaction_SendData.Size(m)
}
func (m *Transaction_SendData) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_SendData.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_SendData proto.InternalMessageInfo

func (m *Transaction_SendData) GetTargetAccount() string {
	if m != nil {
		return m.TargetAccount
	}
	return ""
}

func (m *Transaction_SendData) GetSendAmount() uint64 {
	if m != nil {
		return m.SendAmount
	}
	return 0
}

// SetValidatorFlagContent will contain additional properties when seting the validator flag of an account
type Transaction_SetValidatorFlagContent struct {
	IsValidator          bool     `protobuf:"varint,1,opt,name=is_validator,json=isValidator,proto3" json:"is_validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_SetValidatorFlagContent) Reset()         { *m = Transaction_SetValidatorFlagContent{} }
func (m *Transaction_SetValidatorFlagContent) String() string { return proto.CompactTextString(m) }
func (*Transaction_SetValidatorFlagContent) ProtoMessage()    {}
func (*Transaction_SetValidatorFlagContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 4}
}

func (m *Transaction_SetValidatorFlagContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_SetValidatorFlagContent.Unmarshal(m, b)
}
func (m *Transaction_SetValidatorFlagContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_SetValidatorFlagContent.Marshal(b, m, deterministic)
}
func (m *Transaction_SetValidatorFlagContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_SetValidatorFlagContent.Merge(m, src)
}
func (m *Transaction_SetValidatorFlagContent) XXX_Size() int {
	return xxx_messageInfo_Transaction_SetValidatorFlagContent.Size(m)
}
func (m *Transaction_SetValidatorFlagContent) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_SetValidatorFlagContent.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_SetValidatorFlagContent proto.InternalMessageInfo

func (m *Transaction_SetValidatorFlagContent) GetIsValidator() bool {
	if m != nil {
		return m.IsValidator
	}
	return false
}

// VoteValidatorContent contains the id of the target validator
type Transaction_VoteValidatorContent struct {
	TargetAccount        string   `protobuf:"bytes,1,opt,name=target_account,json=targetAccount,proto3" json:"target_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_VoteValidatorContent) Reset()         { *m = Transaction_VoteValidatorContent{} }
func (m *Transaction_VoteValidatorContent) String() string { return proto.CompactTextString(m) }
func (*Transaction_VoteValidatorContent) ProtoMessage()    {}
func (*Transaction_VoteValidatorContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 5}
}

func (m *Transaction_VoteValidatorContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_VoteValidatorContent.Unmarshal(m, b)
}
func (m *Transaction_VoteValidatorContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_VoteValidatorContent.Marshal(b, m, deterministic)
}
func (m *Transaction_VoteValidatorContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_VoteValidatorContent.Merge(m, src)
}
func (m *Transaction_VoteValidatorContent) XXX_Size() int {
	return xxx_messageInfo_Transaction_VoteValidatorContent.Size(m)
}
func (m *Transaction_VoteValidatorContent) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_VoteValidatorContent.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_VoteValidatorContent proto.InternalMessageInfo

func (m *Transaction_VoteValidatorContent) GetTargetAccount() string {
	if m != nil {
		return m.TargetAccount
	}
	return ""
}

// AddSignerContent contains the new signer
type Transaction_AddSignerContent struct {
	Signer               *Signer  `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_AddSignerContent) Reset()         { *m = Transaction_AddSignerContent{} }
func (m *Transaction_AddSignerContent) String() string { return proto.CompactTextString(m) }
func (*Transaction_AddSignerContent) ProtoMessage()    {}
func (*Transaction_AddSignerContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 6}
}

func (m *Transaction_AddSignerContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_AddSignerContent.Unmarshal(m, b)
}
func (m *Transaction_AddSignerContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_AddSignerContent.Marshal(b, m, deterministic)
}
func (m *Transaction_AddSignerContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_AddSignerContent.Merge(m, src)
}
func (m *Transaction_AddSignerContent) XXX_Size() int {
	return xxx_messageInfo_Transaction_AddSignerContent.Size(m)
}
func (m *Transaction_AddSignerContent) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_AddSignerContent.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_AddSignerContent proto.InternalMessageInfo

func (m *Transaction_AddSignerContent) GetSigner() *Signer {
	if m != nil {
		return m.Signer
	}
	return nil
}

// RemoveSignerContent contains the name of the signer to be removed
type Transaction_RemoveSignerContent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_RemoveSignerContent) Reset()         { *m = Transaction_RemoveSignerContent{} }
func (m *Transaction_RemoveSignerContent) String() string { return proto.CompactTextString(m) }
func (*Transaction_RemoveSignerContent) ProtoMessage()    {}
func (*Transaction_RemoveSignerContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 7}
}

func (m *Transaction_RemoveSignerContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_RemoveSignerContent.Unmarshal(m, b)
}
func (m *Transaction_RemoveSignerContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_RemoveSignerContent.Marshal(b, m, deterministic)
}
func (m *Transaction_RemoveSignerContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_RemoveSignerContent.Merge(m, src)
}
func (m *Transaction_RemoveSignerContent) XXX_Size() int {
	return xxx_messageInfo_Transaction_RemoveSignerContent.Size(m)
}
func (m *Transaction_RemoveSignerContent) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_RemoveSignerContent.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_RemoveSignerContent proto.InternalMessageInfo

func (m *Transaction_RemoveSignerContent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// SetThresholdContent contains the new threshold for the target account
type Transaction_SetThresholdContent struct {
	Threshold            uint64   `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_SetThresholdContent) Reset()         { *m = Transaction_SetThresholdContent{} }
func (m *Transaction_SetThresholdContent) String() string { return proto.CompactTextString(m) }
func (*Transaction_SetThresholdContent) ProtoMessage()    {}
func (*Transaction_SetThresholdContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 8}
}

func (m *Transaction_SetThresholdContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_SetThresholdContent.Unmarshal(m, b)
}
func (m *Transaction_SetThresholdContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_SetThresholdContent.Marshal(b, m, deterministic)
}
func (m *Transaction_SetThresholdContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_SetThresholdContent.Merge(m, src)
}
func (m *Transaction_SetThresholdContent) XXX_Size() int {
	return xxx_messageInfo_Transaction_SetThresholdContent.Size(m)
}
func (m *Transaction_SetThresholdContent) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_SetThresholdContent.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_SetThresholdContent proto.InternalMessageInfo

func (m *Transaction_SetThresholdContent) GetThreshold() uint64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

// SetDataContent contains a key/value pair used to update an account scoped value
type Transaction_SetDataContent struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_SetDataContent) Reset()         { *m = Transaction_SetDataContent{} }
func (m *Transaction_SetDataContent) String() string { return proto.CompactTextString(m) }
func (*Transaction_SetDataContent) ProtoMessage()    {}
func (*Transaction_SetDataContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 9}
}

func (m *Transaction_SetDataContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_SetDataContent.Unmarshal(m, b)
}
func (m *Transaction_SetDataContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_SetDataContent.Marshal(b, m, deterministic)
}
func (m *Transaction_SetDataContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_SetDataContent.Merge(m, src)
}
func (m *Transaction_SetDataContent) XXX_Size() int {
	return xxx_messageInfo_Transaction_SetDataContent.Size(m)
}
func (m *Transaction_SetDataContent) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_SetDataContent.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_SetDataContent proto.InternalMessageInfo

func (m *Transaction_SetDataContent) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Transaction_SetDataContent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// ExecuteContent contains the infos needed to execute a smart contract on the chain
type Transaction_ExecuteContent struct {
	// account of the smart contract
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// key under which the contract can be found on the account
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// type specifies which runtime should be used
	Type Transaction_ExecuteContent_Type `protobuf:"varint,3,opt,name=type,proto3,enum=Transaction_ExecuteContent_Type" json:"type,omitempty"`
	// entrypoint specifies the toplevel function to call in the specified contract
	Entrypoint string `protobuf:"bytes,4,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	// args are supplied to the smart contract
	Args map[string]string `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// compensation contains the amount of native tokens used to pay the smart contract
	Compensation         uint64   `protobuf:"varint,6,opt,name=compensation,proto3" json:"compensation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction_ExecuteContent) Reset()         { *m = Transaction_ExecuteContent{} }
func (m *Transaction_ExecuteContent) String() string { return proto.CompactTextString(m) }
func (*Transaction_ExecuteContent) ProtoMessage()    {}
func (*Transaction_ExecuteContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2, 10}
}

func (m *Transaction_ExecuteContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction_ExecuteContent.Unmarshal(m, b)
}
func (m *Transaction_ExecuteContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction_ExecuteContent.Marshal(b, m, deterministic)
}
func (m *Transaction_ExecuteContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction_ExecuteContent.Merge(m, src)
}
func (m *Transaction_ExecuteContent) XXX_Size() int {
	return xxx_messageInfo_Transaction_ExecuteContent.Size(m)
}
func (m *Transaction_ExecuteContent) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction_ExecuteContent.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction_ExecuteContent proto.InternalMessageInfo

func (m *Transaction_ExecuteContent) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Transaction_ExecuteContent) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Transaction_ExecuteContent) GetType() Transaction_ExecuteContent_Type {
	if m != nil {
		return m.Type
	}
	return Transaction_ExecuteContent_JS
}

func (m *Transaction_ExecuteContent) GetEntrypoint() string {
	if m != nil {
		return m.Entrypoint
	}
	return ""
}

func (m *Transaction_ExecuteContent) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Transaction_ExecuteContent) GetCompensation() uint64 {
	if m != nil {
		return m.Compensation
	}
	return 0
}

// Transactions service response types
type VerifyResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{3}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func (m *VerifyResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *VerifyResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ApplyResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyResponse) Reset()         { *m = ApplyResponse{} }
func (m *ApplyResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyResponse) ProtoMessage()    {}
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{4}
}

func (m *ApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyResponse.Unmarshal(m, b)
}
func (m *ApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyResponse.Marshal(b, m, deterministic)
}
func (m *ApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyResponse.Merge(m, src)
}
func (m *ApplyResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyResponse.Size(m)
}
func (m *ApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyResponse proto.InternalMessageInfo

func (m *ApplyResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *ApplyResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// Accounts service request/response types
type GetAccountRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{5}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetDataRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataRequest) Reset()         { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()    {}
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{6}
}

func (m *GetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRequest.Unmarshal(m, b)
}
func (m *GetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRequest.Marshal(b, m, deterministic)
}
func (m *GetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRequest.Merge(m, src)
}
func (m *GetDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataRequest.Size(m)
}
func (m *GetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRequest proto.InternalMessageInfo

func (m *GetDataRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetDataResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataResponse) Reset()         { *m = GetDataResponse{} }
func (m *GetDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataResponse) ProtoMessage()    {}
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{7}
}

func (m *GetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponse.Unmarshal(m, b)
}
func (m *GetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponse.Marshal(b, m, deterministic)
}
func (m *GetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponse.Merge(m, src)
}
func (m *GetDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataResponse.Size(m)
}
func (m *GetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponse proto.InternalMessageInfo

func (m *GetDataResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetDataResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListDataRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Prefix               string   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDataRequest) Reset()         { *m = ListDataRequest{} }
func (m *ListDataRequest) String() string { return proto.CompactTextString(m) }
func (*ListDataRequest) ProtoMessage()    {}
func (*ListDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{8}
}

func (m *ListDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDataRequest.Unmarshal(m, b)
}
func (m *ListDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDataRequest.Marshal(b, m, deterministic)
}
func (m *ListDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDataRequest.Merge(m, src)
}
func (m *ListDataRequest) XXX_Size() int {
	return xxx_messageInfo_ListDataRequest.Size(m)
}
func (m *ListDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDataRequest proto.InternalMessageInfo

func (m *ListDataRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListDataRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

// Validators service request/response types
type ListValidatorsRequest struct {
	TopN                 uint64   `protobuf:"varint,1,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListValidatorsRequest) Reset()         { *m = ListValidatorsRequest{} }
func (m *ListValidatorsRequest) String() string { return proto.CompactTextString(m) }
func (*ListValidatorsRequest) ProtoMessage()    {}
func (*ListValidatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{9}
}

func (m *ListValidatorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListValidatorsRequest.Unmarshal(m, b)
}
func (m *ListValidatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListValidatorsRequest.Marshal(b, m, deterministic)
}
func (m *ListValidatorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListValidatorsRequest.Merge(m, src)
}
func (m *ListValidatorsRequest) XXX_Size() int {
	return xxx_messageInfo_ListValidatorsRequest.Size(m)
}
func (m *ListValidatorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListValidatorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListValidatorsRequest proto.InternalMessageInfo

func (m *ListValidatorsRequest) GetTopN() uint64 {
	if m != nil {
		return m.TopN
	}
	return 0
}

type Validator struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stake                uint64   `protobuf:"varint,2,opt,name=stake,proto3" json:"stake,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{10}
}

func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Validator) GetStake() uint64 {
	if m != nil {
		return m.Stake
	}
	return 0
}

type ListValidatorsResponse struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListValidatorsResponse) Reset()         { *m = ListValidatorsResponse{} }
func (m *ListValidatorsResponse) String() string { return proto.CompactTextString(m) }
func (*ListValidatorsResponse) ProtoMessage()    {}
func (*ListValidatorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{11}
}

func (m *ListValidatorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListValidatorsResponse.Unmarshal(m, b)
}
func (m *ListValidatorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListValidatorsResponse.Marshal(b, m, deterministic)
}
func (m *ListValidatorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListValidatorsResponse.Merge(m, src)
}
func (m *ListValidatorsResponse) XXX_Size() int {
	return xxx_messageInfo_ListValidatorsResponse.Size(m)
}
func (m *ListValidatorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListValidatorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListValidatorsResponse proto.InternalMessageInfo

func (m *ListValidatorsResponse) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type GetValidatorsRequest struct {
	TopN                 uint64   `protobuf:"varint,1,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	Block                uint64   `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValidatorsRequest) Reset()         { *m = GetValidatorsRequest{} }
func (m *GetValidatorsRequest) String() string { return proto.CompactTextString(m) }
func (*GetValidatorsRequest) ProtoMessage()    {}
func (*GetValidatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{12}
}

func (m *GetValidatorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorsRequest.Unmarshal(m, b)
}
func (m *GetValidatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorsRequest.Marshal(b, m, deterministic)
}
func (m *GetValidatorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorsRequest.Merge(m, src)
}
func (m *GetValidatorsRequest) XXX_Size() int {
	return xxx_messageInfo_GetValidatorsRequest.Size(m)
}
func (m *GetValidatorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorsRequest proto.InternalMessageInfo

func (m *GetValidatorsRequest) GetTopN() uint64 {
	if m != nil {
		return m.TopN
	}
	return 0
}

func (m *GetValidatorsRequest) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

type GetValidatorsResponse struct {
	Validator            *Validator   `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Witnesses            []*Validator `protobuf:"bytes,2,rep,name=witnesses,proto3" json:"witnesses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetValidatorsResponse) Reset()         { *m = GetValidatorsResponse{} }
func (m *GetValidatorsResponse) String() string { return proto.CompactTextString(m) }
func (*GetValidatorsResponse) ProtoMessage()    {}
func (*GetValidatorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{13}
}

func (m *GetValidatorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorsResponse.Unmarshal(m, b)
}
func (m *GetValidatorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorsResponse.Marshal(b, m, deterministic)
}
func (m *GetValidatorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorsResponse.Merge(m, src)
}
func (m *GetValidatorsResponse) XXX_Size() int {
	return xxx_messageInfo_GetValidatorsResponse.Size(m)
}
func (m *GetValidatorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorsResponse proto.InternalMessageInfo

func (m *GetValidatorsResponse) GetValidator() *Validator {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *GetValidatorsResponse) GetWitnesses() []*Validator {
	if m != nil {
		return m.Witnesses
	}
	return nil
}

func init() {
	proto.RegisterEnum("Transaction_Type", Transaction_Type_name, Transaction_Type_value)
	proto.RegisterEnum("Transaction_ExecuteContent_Type", Transaction_ExecuteContent_Type_name, Transaction_ExecuteContent_Type_value)
	proto.RegisterType((*Signer)(nil), "Signer")
	proto.RegisterType((*Account)(nil), "Account")
	proto.RegisterMapType((map[string]*Signer)(nil), "Account.SignersEntry")
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterMapType((map[string][]byte)(nil), "Transaction.SignaturesEntry")
	proto.RegisterType((*Transaction_GenesisContent)(nil), "Transaction.GenesisContent")
	proto.RegisterType((*Transaction_CreateAccountContent)(nil), "Transaction.CreateAccountContent")
	proto.RegisterType((*Transaction_MergeAccountContent)(nil), "Transaction.MergeAccountContent")
	proto.RegisterType((*Transaction_SendData)(nil), "Transaction.SendData")
	proto.RegisterType((*Transaction_SetValidatorFlagContent)(nil), "Transaction.SetValidatorFlagContent")
	proto.RegisterType((*Transaction_VoteValidatorContent)(nil), "Transaction.VoteValidatorContent")
	proto.RegisterType((*Transaction_AddSignerContent)(nil), "Transaction.AddSignerContent")
	proto.RegisterType((*Transaction_RemoveSignerContent)(nil), "Transaction.RemoveSignerContent")
	proto.RegisterType((*Transaction_SetThresholdContent)(nil), "Transaction.SetThresholdContent")
	proto.RegisterType((*Transaction_SetDataContent)(nil), "Transaction.SetDataContent")
	proto.RegisterType((*Transaction_ExecuteContent)(nil), "Transaction.ExecuteContent")
	proto.RegisterMapType((map[string]string)(nil), "Transaction.ExecuteContent.ArgsEntry")
	proto.RegisterType((*VerifyResponse)(nil), "VerifyResponse")
	proto.RegisterType((*ApplyResponse)(nil), "ApplyResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "GetAccountRequest")
	proto.RegisterType((*GetDataRequest)(nil), "GetDataRequest")
	proto.RegisterType((*GetDataResponse)(nil), "GetDataResponse")
	proto.RegisterType((*ListDataRequest)(nil), "ListDataRequest")
	proto.RegisterType((*ListValidatorsRequest)(nil), "ListValidatorsRequest")
	proto.RegisterType((*Validator)(nil), "Validator")
	proto.RegisterType((*ListValidatorsResponse)(nil), "ListValidatorsResponse")
	proto.RegisterType((*GetValidatorsRequest)(nil), "GetValidatorsRequest")
	proto.RegisterType((*GetValidatorsResponse)(nil), "GetValidatorsResponse")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 1478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xeb, 0x6e, 0xdb, 0x36,
	0x14, 0xae, 0x7c, 0xf7, 0xb1, 0xe3, 0x28, 0xcc, 0xa5, 0x86, 0xd6, 0xae, 0xae, 0xd6, 0xa0, 0xd9,
	0x50, 0x28, 0x9d, 0x5b, 0xac, 0x6b, 0xd1, 0x0c, 0x50, 0x63, 0xd5, 0xe9, 0x90, 0x0b, 0x40, 0xbb,
	0xd9, 0xe5, 0xc7, 0x0c, 0xc6, 0x66, 0x1c, 0x21, 0xb6, 0xe4, 0x89, 0x74, 0xda, 0x60, 0x0f, 0xb1,
	0x97, 0xe8, 0x8b, 0x0c, 0xd8, 0x5b, 0xec, 0x65, 0x06, 0x52, 0x17, 0x4b, 0xb2, 0xda, 0x66, 0xfb,
	0x27, 0x7e, 0xfc, 0xf8, 0xf9, 0x5c, 0x79, 0x68, 0x80, 0xa1, 0xeb, 0x51, 0x63, 0xe6, 0xb9, 0xdc,
	0xd5, 0xee, 0x8d, 0x5d, 0x77, 0x3c, 0xa1, 0xbb, 0x72, 0x75, 0x36, 0x3f, 0xdf, 0xe5, 0xf6, 0x94,
	0x32, 0x4e, 0xa6, 0x33, 0x9f, 0xa0, 0x7f, 0x50, 0xa0, 0xd4, 0xb3, 0xc7, 0x0e, 0xf5, 0x10, 0x82,
	0x82, 0x43, 0xa6, 0xb4, 0xa9, 0xb4, 0x94, 0x9d, 0x2a, 0x96, 0xdf, 0x68, 0x17, 0xd6, 0x99, 0x3d,
	0x76, 0x08, 0x9f, 0x7b, 0x74, 0x40, 0x26, 0x63, 0xd7, 0xb3, 0xf9, 0xc5, 0xb4, 0x99, 0x93, 0x14,
	0x14, 0x6d, 0x99, 0xe1, 0x0e, 0xda, 0x86, 0xc6, 0x05, 0x61, 0x17, 0x31, 0x6e, 0x5e, 0x72, 0x57,
	0x04, 0xba, 0xa0, 0x6d, 0x41, 0x69, 0x36, 0x3f, 0xbb, 0xa4, 0xd7, 0xcd, 0x42, 0x4b, 0xd9, 0xa9,
	0xe3, 0x60, 0x25, 0xf0, 0x77, 0xd4, 0x1e, 0x5f, 0xf0, 0x66, 0xb1, 0xa5, 0xec, 0x14, 0x70, 0xb0,
	0xd2, 0xff, 0xc9, 0x41, 0xd9, 0x1c, 0x0e, 0xdd, 0xb9, 0xc3, 0x51, 0x03, 0x72, 0xf6, 0x28, 0xb0,
	0x32, 0x67, 0x8f, 0x50, 0x0b, 0x6a, 0x23, 0xca, 0x86, 0x9e, 0x3d, 0xe3, 0xb6, 0xeb, 0x04, 0xb6,
	0xc5, 0x21, 0xb4, 0x0b, 0x65, 0x26, 0x7d, 0x64, 0xcd, 0x7c, 0x2b, 0xbf, 0x53, 0x6b, 0x6f, 0x1a,
	0x81, 0x98, 0xe1, 0xfb, 0xce, 0x2c, 0x87, 0x7b, 0xd7, 0x38, 0x64, 0xa1, 0x3b, 0x50, 0xe5, 0x17,
	0x1e, 0x65, 0x17, 0xee, 0x64, 0x24, 0x2d, 0x2c, 0xe0, 0x05, 0x80, 0x9a, 0x50, 0x3e, 0x23, 0x13,
	0xe2, 0x0c, 0x69, 0x60, 0x65, 0xb8, 0x44, 0xf7, 0xa1, 0x6e, 0xb3, 0xc1, 0x15, 0x99, 0xd8, 0x23,
	0xc2, 0x5d, 0xaf, 0x59, 0x6a, 0x29, 0x3b, 0x15, 0x5c, 0xb3, 0xd9, 0x69, 0x08, 0x89, 0x28, 0x5f,
	0xb9, 0x9c, 0x36, 0xcb, 0x7e, 0x94, 0xc5, 0x37, 0x7a, 0x0e, 0x30, 0xf4, 0x28, 0xe1, 0x74, 0x34,
	0x20, 0xbc, 0x59, 0x69, 0x29, 0x3b, 0xb5, 0xb6, 0x66, 0xf8, 0xa9, 0x33, 0xc2, 0xd4, 0x19, 0xfd,
	0x30, 0x75, 0xb8, 0x1a, 0xb0, 0x4d, 0xae, 0xed, 0x43, 0x3d, 0xee, 0x02, 0x52, 0x21, 0x2f, 0xa2,
	0xea, 0x47, 0x47, 0x7c, 0xa2, 0xbb, 0x50, 0xbc, 0x22, 0x93, 0x39, 0x95, 0x81, 0xa9, 0xb5, 0xcb,
	0x81, 0xcb, 0xd8, 0x47, 0x5f, 0xe4, 0xbe, 0x57, 0xf4, 0x0f, 0x08, 0x6a, 0x7d, 0x8f, 0x38, 0x8c,
	0x0c, 0x65, 0xbc, 0xd2, 0x11, 0xde, 0x86, 0x02, 0xbf, 0x9e, 0xf9, 0x0a, 0x8d, 0xf6, 0x9a, 0x11,
	0xe3, 0x1a, 0xfd, 0xeb, 0x19, 0xc5, 0x72, 0x5b, 0xe4, 0x9e, 0xb9, 0x73, 0x6f, 0x48, 0x07, 0xc4,
	0x8f, 0x6e, 0x98, 0x7b, 0x1f, 0x0d, 0xf3, 0x97, 0xf4, 0xb6, 0xf0, 0x1f, 0xbc, 0x45, 0x2f, 0x01,
	0xa2, 0x9a, 0x63, 0xcd, 0xa2, 0xcc, 0xe5, 0x9d, 0x84, 0x39, 0xbd, 0x68, 0xdb, 0x4f, 0x69, 0x8c,
	0x2f, 0x42, 0x7f, 0x4e, 0x29, 0x93, 0x59, 0x29, 0x60, 0xf9, 0x8d, 0x7e, 0x81, 0x2d, 0x5f, 0x3e,
	0xb4, 0x79, 0x30, 0x74, 0x1d, 0x4e, 0x1d, 0x2e, 0x13, 0x54, 0x6b, 0xdf, 0x4f, 0xa8, 0xef, 0x4b,
	0x6a, 0xe0, 0xc8, 0xbe, 0x4f, 0x3c, 0xb8, 0x85, 0x37, 0x86, 0x19, 0x38, 0x3a, 0x85, 0xcd, 0x29,
	0xf5, 0xc6, 0xcb, 0xca, 0x7e, 0x82, 0x5b, 0x09, 0xe5, 0x23, 0xc1, 0x5c, 0x12, 0x5e, 0x9f, 0x2e,
	0xc3, 0xe8, 0x05, 0xd4, 0x19, 0x75, 0x46, 0x91, 0x5c, 0x55, 0xca, 0x6d, 0x26, 0xc3, 0x40, 0x9d,
	0x51, 0x87, 0x70, 0x72, 0x70, 0x0b, 0xd7, 0x04, 0x39, 0x3c, 0x3b, 0x04, 0x8d, 0x51, 0xbe, 0xa8,
	0xd0, 0xc1, 0xf9, 0x84, 0x8c, 0x23, 0x25, 0x90, 0x4a, 0x0f, 0x52, 0x4a, 0x3c, 0x2a, 0xde, 0xd7,
	0x13, 0x32, 0x5e, 0x18, 0x77, 0x9b, 0x65, 0x6f, 0x89, 0x98, 0x8a, 0xb2, 0x8e, 0xfd, 0x4a, 0xf8,
	0x03, 0xb5, 0x8c, 0x98, 0x9e, 0xba, 0x9c, 0x46, 0x32, 0xb1, 0x98, 0x5e, 0x65, 0xe0, 0xe8, 0x08,
	0x10, 0x19, 0x8d, 0x06, 0x7e, 0x9f, 0x46, 0xb2, 0x75, 0x29, 0x7b, 0x37, 0x21, 0x6b, 0x8e, 0x46,
	0x7e, 0xa1, 0x2f, 0x24, 0x55, 0x92, 0xc2, 0x44, 0x8a, 0x3c, 0x3a, 0x75, 0xaf, 0x68, 0x5a, 0x71,
	0x25, 0x23, 0x45, 0x58, 0x32, 0xd3, 0xa2, 0xeb, 0xde, 0x32, 0x2c, 0x74, 0x45, 0x98, 0xa3, 0x2b,
	0x23, 0xd2, 0x6d, 0x64, 0xe8, 0xf6, 0x28, 0xef, 0x87, 0xc4, 0x98, 0x2e, 0x5b, 0x86, 0x51, 0x17,
	0x54, 0xa1, 0x3b, 0x22, 0x9c, 0x44, 0x92, 0xab, 0x52, 0xf2, 0x8b, 0xb4, 0xa4, 0xc8, 0xfe, 0x42,
	0xad, 0xc1, 0x12, 0x08, 0x7a, 0x0d, 0xab, 0xf4, 0x3d, 0x1d, 0xce, 0x39, 0x8d, 0x74, 0xd4, 0x0c,
	0x1d, 0xcb, 0xe7, 0xc4, 0x74, 0x68, 0x02, 0x11, 0x3a, 0x63, 0xea, 0x50, 0x66, 0xb3, 0x48, 0x67,
	0x2d, 0x43, 0xa7, 0xeb, 0x73, 0x62, 0x3a, 0xe3, 0x04, 0xa2, 0x7d, 0x07, 0x8d, 0x24, 0x07, 0x3d,
	0x80, 0x4a, 0xd0, 0x37, 0xac, 0xa9, 0xc8, 0x46, 0xaf, 0x84, 0x97, 0x36, 0x8e, 0x76, 0xb4, 0x17,
	0xb0, 0x91, 0xd5, 0x93, 0x48, 0x87, 0x72, 0x78, 0x07, 0x29, 0xd2, 0x9e, 0xc5, 0xe1, 0x70, 0x43,
	0x7b, 0x09, 0xeb, 0x19, 0x5d, 0x27, 0x6e, 0x31, 0x4e, 0xbc, 0x31, 0xe5, 0x83, 0xb8, 0x42, 0x15,
	0xaf, 0xf8, 0x68, 0xc0, 0xd6, 0x30, 0x54, 0xc2, 0x26, 0xbb, 0xe1, 0x11, 0x74, 0x0f, 0x64, 0x2f,
	0x0e, 0xc8, 0x54, 0x72, 0x72, 0xf2, 0x1a, 0x02, 0x01, 0x99, 0xd3, 0xc0, 0xa2, 0xdb, 0x1f, 0x69,
	0xb7, 0xa5, 0xc9, 0xa2, 0x2c, 0x4d, 0x16, 0x6d, 0x0f, 0x36, 0xb2, 0x7a, 0xe9, 0xa6, 0x0e, 0x3d,
	0x01, 0x35, 0xdd, 0x33, 0xe8, 0x1e, 0x94, 0xfc, 0xc6, 0x08, 0xa2, 0x18, 0x0d, 0x8f, 0x00, 0xd6,
	0xbe, 0x86, 0xf5, 0x8c, 0xb6, 0xc8, 0x7a, 0x4a, 0x68, 0x4f, 0x60, 0x3d, 0xa3, 0xd2, 0x93, 0xa3,
	0x36, 0x97, 0x1a, 0xb5, 0xa2, 0x2e, 0x92, 0xb5, 0x9c, 0x31, 0xe0, 0x10, 0x14, 0x44, 0x43, 0xc8,
	0xc3, 0x75, 0x2c, 0xbf, 0xb5, 0xbf, 0x73, 0xd0, 0x48, 0x16, 0xaf, 0x98, 0xda, 0x49, 0xff, 0xc3,
	0x65, 0x28, 0x99, 0x5b, 0x48, 0x3e, 0x0d, 0x06, 0x5e, 0x5e, 0x0e, 0xbc, 0xd6, 0x27, 0x7a, 0x22,
	0x3e, 0xff, 0xbe, 0x04, 0xa0, 0x62, 0xe8, 0xcc, 0x5c, 0xdb, 0xf1, 0x07, 0x5b, 0x15, 0xc7, 0x10,
	0xf4, 0x1c, 0x0a, 0xc4, 0x1b, 0x87, 0x73, 0x6b, 0xfb, 0x53, 0xaa, 0xa6, 0x37, 0x0e, 0x06, 0x98,
	0x3c, 0x82, 0x74, 0xa8, 0x0f, 0xdd, 0xe9, 0x8c, 0x3a, 0x8c, 0xc8, 0x47, 0x8e, 0x3f, 0xc2, 0x12,
	0x98, 0xf6, 0x0c, 0xaa, 0xd1, 0xb1, 0x8c, 0x30, 0x6d, 0xc4, 0xdf, 0x01, 0xd5, 0xf8, 0xf8, 0x6f,
	0x42, 0x41, 0x78, 0x81, 0x4a, 0x90, 0xfb, 0xb1, 0xa7, 0xde, 0x42, 0x15, 0x28, 0xfc, 0x64, 0xf6,
	0x8e, 0x54, 0x45, 0xdb, 0x83, 0xd5, 0xd4, 0x40, 0xfd, 0x9c, 0x70, 0x3d, 0x2e, 0xfc, 0x97, 0x12,
	0x28, 0xd7, 0xa0, 0xdc, 0xb5, 0x8e, 0xad, 0xde, 0x1b, 0x21, 0x8f, 0xa0, 0xb1, 0x8f, 0x2d, 0xb3,
	0x6f, 0x0d, 0xcc, 0xfd, 0xfd, 0x93, 0xb7, 0xc7, 0x7d, 0x55, 0x41, 0x6b, 0xb0, 0x72, 0x64, 0xe1,
	0xee, 0x02, 0xca, 0x09, 0x2b, 0x7a, 0xd6, 0x71, 0x47, 0xcd, 0xa3, 0x2d, 0x40, 0x3d, 0xab, 0x3f,
	0x38, 0x35, 0x0f, 0xdf, 0x74, 0xcc, 0xfe, 0x09, 0x1e, 0xbc, 0x3e, 0x34, 0xbb, 0x6a, 0x41, 0x08,
	0x9d, 0x9e, 0xf4, 0xad, 0xc5, 0x86, 0x5a, 0x44, 0x0d, 0x00, 0xb3, 0xd3, 0x19, 0xf4, 0xde, 0x74,
	0x8f, 0x2d, 0xac, 0x96, 0x84, 0x30, 0xb6, 0x8e, 0x4e, 0x4e, 0xad, 0x10, 0x2a, 0x0b, 0x48, 0xc8,
	0xf5, 0x0f, 0xb0, 0xd5, 0x3b, 0x38, 0x39, 0xec, 0xa8, 0x15, 0x54, 0x87, 0x8a, 0x80, 0x3a, 0x66,
	0xdf, 0x54, 0xab, 0xc2, 0x5a, 0xeb, 0x67, 0x6b, 0xff, 0x6d, 0xdf, 0x52, 0xe1, 0x55, 0x15, 0xca,
	0xc1, 0xcd, 0xa6, 0xff, 0x00, 0x8d, 0x53, 0xea, 0xd9, 0xe7, 0xd7, 0x98, 0xb2, 0x99, 0xeb, 0x30,
	0x1a, 0xb8, 0x1e, 0xbc, 0x95, 0x2a, 0xd8, 0x5f, 0x88, 0x47, 0xac, 0x47, 0x09, 0x8b, 0xde, 0xa2,
	0xc1, 0x4a, 0xdf, 0x83, 0x15, 0x73, 0x36, 0x9b, 0xfc, 0xdf, 0xe3, 0x0f, 0x61, 0xad, 0x1b, 0xb5,
	0x2b, 0xa6, 0xbf, 0xcf, 0x29, 0xcb, 0xec, 0x34, 0x5d, 0x5e, 0xa6, 0xb2, 0x69, 0x3e, 0xc1, 0x5a,
	0xae, 0x7a, 0xfd, 0x19, 0xac, 0x46, 0xe7, 0x02, 0x0b, 0x6f, 0xd4, 0x6d, 0xfa, 0x1e, 0xac, 0x1e,
	0xda, 0xec, 0xb3, 0xbf, 0x28, 0x1e, 0xfd, 0x1e, 0x3d, 0xb7, 0xdf, 0x87, 0x8e, 0xf9, 0x2b, 0xfd,
	0x11, 0x6c, 0x8a, 0xe3, 0xd1, 0xc5, 0xc5, 0x42, 0x91, 0x75, 0x28, 0x72, 0x77, 0x36, 0x70, 0xa4,
	0x4a, 0x01, 0x17, 0xb8, 0x3b, 0x3b, 0xd6, 0xbf, 0x85, 0xea, 0xe2, 0x35, 0x9d, 0x7e, 0xa9, 0x6e,
	0x40, 0x91, 0x71, 0x72, 0x49, 0x83, 0x9b, 0xc4, 0x5f, 0xe8, 0x1d, 0xd8, 0x4a, 0xff, 0x40, 0xe0,
	0xdf, 0x37, 0x00, 0xd1, 0x9d, 0x1a, 0xce, 0x19, 0x30, 0x22, 0x22, 0x8e, 0xed, 0xea, 0x26, 0x6c,
	0x74, 0xe9, 0x0d, 0xad, 0x14, 0x86, 0x9c, 0x4d, 0xdc, 0xe1, 0x65, 0x68, 0x88, 0x5c, 0xe8, 0x97,
	0xb0, 0x99, 0x92, 0x08, 0xec, 0xd8, 0x81, 0x6a, 0xf2, 0x6e, 0x4f, 0x9a, 0xb1, 0xd8, 0x14, 0xcc,
	0x77, 0x36, 0x77, 0x28, 0x63, 0x94, 0x35, 0x73, 0x4b, 0x06, 0x2f, 0x36, 0xdb, 0xbf, 0x41, 0x3d,
	0x76, 0xc3, 0x30, 0xf4, 0x10, 0x4a, 0x7e, 0xf9, 0xa2, 0x7a, 0xfc, 0xea, 0xd1, 0x56, 0x8d, 0x54,
	0x55, 0x6f, 0x43, 0x51, 0xd6, 0x69, 0x8a, 0xd7, 0x30, 0x12, 0xd5, 0xdb, 0xfe, 0x53, 0x81, 0x4a,
	0x50, 0x8d, 0x0c, 0x7d, 0x05, 0xf9, 0x2e, 0xe5, 0x08, 0x19, 0x4b, 0x25, 0xaa, 0x45, 0xa3, 0x17,
	0x3d, 0x82, 0x72, 0x50, 0x60, 0x68, 0xd5, 0x48, 0x96, 0xa8, 0xa6, 0x1a, 0xe9, 0xda, 0x7b, 0x0c,
	0x95, 0xb0, 0xaa, 0x90, 0x6a, 0xa4, 0x0a, 0x6c, 0x99, 0xff, 0x58, 0x69, 0xff, 0x01, 0xb0, 0x88,
	0x2d, 0x7a, 0x06, 0x05, 0x71, 0x08, 0x6d, 0x19, 0x99, 0xd5, 0xa5, 0xdd, 0x36, 0x3e, 0x52, 0x14,
	0x4f, 0x7d, 0x5f, 0x36, 0x8d, 0xac, 0x74, 0x6b, 0x5b, 0x46, 0x66, 0x0a, 0x5f, 0x15, 0x7f, 0xcd,
	0x93, 0x99, 0x7d, 0x56, 0x92, 0xff, 0x60, 0x9e, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x19,
	0x67, 0xbd, 0x86, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionsClient is the client API for Transactions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionsClient interface {
	// Verify checks if all needed signatures are in place + all prerequirements are fullfilled for this TX to be executed
	// This includes existence and balance checks.
	Verify(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*VerifyResponse, error)
	// Apply applies a transaction against the current ledger state
	Apply(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*ApplyResponse, error)
}

type transactionsClient struct {
	cc *grpc.ClientConn
}

func NewTransactionsClient(cc *grpc.ClientConn) TransactionsClient {
	return &transactionsClient{cc}
}

func (c *transactionsClient) Verify(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/Transactions/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsClient) Apply(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*ApplyResponse, error) {
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, "/Transactions/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionsServer is the server API for Transactions service.
type TransactionsServer interface {
	// Verify checks if all needed signatures are in place + all prerequirements are fullfilled for this TX to be executed
	// This includes existence and balance checks.
	Verify(context.Context, *Transaction) (*VerifyResponse, error)
	// Apply applies a transaction against the current ledger state
	Apply(context.Context, *Transaction) (*ApplyResponse, error)
}

// UnimplementedTransactionsServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionsServer struct {
}

func (*UnimplementedTransactionsServer) Verify(ctx context.Context, req *Transaction) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (*UnimplementedTransactionsServer) Apply(ctx context.Context, req *Transaction) (*ApplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apply not implemented")
}

func RegisterTransactionsServer(s *grpc.Server, srv TransactionsServer) {
	s.RegisterService(&_Transactions_serviceDesc, srv)
}

func _Transactions_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Transactions/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServer).Verify(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transactions_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Transactions/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServer).Apply(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transactions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Transactions",
	HandlerType: (*TransactionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _Transactions_Verify_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _Transactions_Apply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}

// AccountsClient is the client API for Accounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsClient interface {
	// Get returns a single account
	Get(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error)
	// GetData returns a single data object
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
	// ListData returns a stream of data objects attached to the specified account
	ListData(ctx context.Context, in *ListDataRequest, opts ...grpc.CallOption) (Accounts_ListDataClient, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) Get(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/Accounts/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, "/Accounts/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) ListData(ctx context.Context, in *ListDataRequest, opts ...grpc.CallOption) (Accounts_ListDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Accounts_serviceDesc.Streams[0], "/Accounts/ListData", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountsListDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Accounts_ListDataClient interface {
	Recv() (*GetDataResponse, error)
	grpc.ClientStream
}

type accountsListDataClient struct {
	grpc.ClientStream
}

func (x *accountsListDataClient) Recv() (*GetDataResponse, error) {
	m := new(GetDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AccountsServer is the server API for Accounts service.
type AccountsServer interface {
	// Get returns a single account
	Get(context.Context, *GetAccountRequest) (*Account, error)
	// GetData returns a single data object
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	// ListData returns a stream of data objects attached to the specified account
	ListData(*ListDataRequest, Accounts_ListDataServer) error
}

// UnimplementedAccountsServer can be embedded to have forward compatible implementations.
type UnimplementedAccountsServer struct {
}

func (*UnimplementedAccountsServer) Get(ctx context.Context, req *GetAccountRequest) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedAccountsServer) GetData(ctx context.Context, req *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (*UnimplementedAccountsServer) ListData(req *ListDataRequest, srv Accounts_ListDataServer) error {
	return status.Errorf(codes.Unimplemented, "method ListData not implemented")
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Accounts/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Get(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Accounts/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_ListData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountsServer).ListData(m, &accountsListDataServer{stream})
}

type Accounts_ListDataServer interface {
	Send(*GetDataResponse) error
	grpc.ServerStream
}

type accountsListDataServer struct {
	grpc.ServerStream
}

func (x *accountsListDataServer) Send(m *GetDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Accounts_Get_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _Accounts_GetData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListData",
			Handler:       _Accounts_ListData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core.proto",
}

// ValidatorsClient is the client API for Validators service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ValidatorsClient interface {
	// List returns a sorted list of the top N validators
	List(ctx context.Context, in *ListValidatorsRequest, opts ...grpc.CallOption) (*ListValidatorsResponse, error)
	// Get returns the validator and witnesses for a given block under the probalilities implied by the current state
	Get(ctx context.Context, in *GetValidatorsRequest, opts ...grpc.CallOption) (*GetValidatorsResponse, error)
}

type validatorsClient struct {
	cc *grpc.ClientConn
}

func NewValidatorsClient(cc *grpc.ClientConn) ValidatorsClient {
	return &validatorsClient{cc}
}

func (c *validatorsClient) List(ctx context.Context, in *ListValidatorsRequest, opts ...grpc.CallOption) (*ListValidatorsResponse, error) {
	out := new(ListValidatorsResponse)
	err := c.cc.Invoke(ctx, "/Validators/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validatorsClient) Get(ctx context.Context, in *GetValidatorsRequest, opts ...grpc.CallOption) (*GetValidatorsResponse, error) {
	out := new(GetValidatorsResponse)
	err := c.cc.Invoke(ctx, "/Validators/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidatorsServer is the server API for Validators service.
type ValidatorsServer interface {
	// List returns a sorted list of the top N validators
	List(context.Context, *ListValidatorsRequest) (*ListValidatorsResponse, error)
	// Get returns the validator and witnesses for a given block under the probalilities implied by the current state
	Get(context.Context, *GetValidatorsRequest) (*GetValidatorsResponse, error)
}

// UnimplementedValidatorsServer can be embedded to have forward compatible implementations.
type UnimplementedValidatorsServer struct {
}

func (*UnimplementedValidatorsServer) List(ctx context.Context, req *ListValidatorsRequest) (*ListValidatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedValidatorsServer) Get(ctx context.Context, req *GetValidatorsRequest) (*GetValidatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterValidatorsServer(s *grpc.Server, srv ValidatorsServer) {
	s.RegisterService(&_Validators_serviceDesc, srv)
}

func _Validators_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Validators/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorsServer).List(ctx, req.(*ListValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Validators_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidatorsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Validators/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidatorsServer).Get(ctx, req.(*GetValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Validators_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Validators",
	HandlerType: (*ValidatorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Validators_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Validators_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}
